### ISSUE TITLE
Go through Google Drive and Pull Over Resources 

### ISSUE THREAD

**Issue by DevanBurke** [CAWaterBoardDataCenter/equity-data-handbook#3]
https://drive.google.com/drive/folders/1LzaenYMQq-Uaalzxd8luKDaTQncklSqK

**Comment by DevanBurke** [comment]
OIMA Equity Project Brain Dump: https://docs.google.com/document/d/1ROgPiIVGq5Py87XyL9CdSZlbCJGKdw8Z/edit

**Comment by DevanBurke** [comment]
Census Training Resources: https://drive.google.com/drive/folders/1evETer9IiU1LyyIpPJz1cFFiVa4-bhro

**Comment by AHolder1** [comment]
After each resources is complete - recommend change share settings so no one can view the link or add a note at the top of the doc stating that this is an old link and a more up to date version can be found
[here](https://cawaterboarddatacenter.github.io/equity-data-handbook/)...or maybe we just delete the Google Drive altogether?

**Comment by AHolder1** [comment]
@DevanBurke - it looks like you're the owner of the [Best Practices Doc](https://docs.google.com/document/d/15wJl81LcFuQHhJUxCXfOvZuT7hCNAlQ237GtiiQpPdM/edit?usp=drive_link) - everything has been pulled over so you can change the share settings or delete at your leisure.

@NMartorano same goes for you for the [brain dump](https://docs.google.com/document/d/1ROgPiIVGq5Py87XyL9CdSZlbCJGKdw8Z/edit?usp=drive_link&ouid=117159529109751701858&rtpof=true&sd=true) and [Project form guidance](https://docs.google.com/document/d/1w9y9Oh818Lm2-S0GSKW2s1p6lU-2NbLiXQp-3Jq9YBE/edit?usp=drive_link)

I moved the census training resources to a different issue since that will take a bit more time - but everything else is ready to be archived/deleted!
